#30 Add missing RIPE API methods
ripe-tech/ripe-api pull request #31
Opened 2021-11-26 17:37 UTC by 3rdvision

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-api/issues/30 |
| Decisions | - Add missing endpoint methods according to RIPE SDK method collection. |

2021-11-29 20:56 UTC, NFSS10 commented
@3rdvision Why is this in draft?

2021-11-30 08:50 UTC, joamag requested changes

2021-11-30 08:50 UTC, joamag commented on src/ripe/transport_rule.py
> +    def get_transport_rules(self, *args, **kwargs):
list

2021-11-30 08:50 UTC, joamag commented on src/ripe/sku.py
> +    def get_skus(self):
list_skus

2021-11-30 08:50 UTC, joamag commented on setup.py
> +    version = "0.5.0",
we should not change versions in feature PRs

2021-11-30 08:50 UTC, joamag commented on src/ripe/availability_rule.py
> +    def get_availability_rules(self, *args, **kwargs):
list_availability_rules

2021-11-30 09:38 UTC, joamag requested changes

2021-11-30 09:38 UTC, joamag commented on src/ripe/availability_rule.py
> +    def get_availability_rule(self, id):
the order of the methods should be LCRUD

2021-11-30 10:07 UTC, joamag requested changes

2021-11-30 10:07 UTC, joamag commented on src/ripe/order.py
> +    def quality_assure_order(
Please be aware of proper sorting of methods, the quality assure should be together with the ready, produce, etc. methods

2021-11-30 10:13 UTC, joamag requested changes

2021-11-30 10:13 UTC, joamag commented on src/ripe/build.py
> +#!/usr/bin/python
remove this API for now, we don't want the build API to get exposed for now

2021-11-30 10:20 UTC, joamag requested changes

2021-11-30 10:20 UTC, joamag commented on src/ripe/base.py
> +        self.key = kwargs.get("key", None)
we don't want to suport this approach, please remove key references

2021-11-30 11:25 UTC, joamag approved these changes

2021-11-30 11:25 UTC, merged